DROP SCHEMA IF EXISTS fitzone CASCADE;
CREATE SCHEMA fitzone;
SET search_path TO fitzone;

CREATE TABLE activity_types (
    idactivitytype INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description TEXT
);

CREATE TABLE duration_types (
    iddurationtype INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description TEXT
);

CREATE TABLE course_types (
    idcoursetype INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description TEXT
);

CREATE TABLE rooms (
    idroom INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    capacity INT NOT NULL,
    is_weight_room BOOLEAN DEFAULT FALSE
);

CREATE TABLE membership_types (
    idmembershiptype INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    idactivitytype INT NOT NULL REFERENCES activity_types(idactivitytype),
    iddurationtype INT NOT NULL REFERENCES duration_types(iddurationtype)
);

CREATE TABLE users (
    iduser INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE athletes (
    idathlete INT PRIMARY KEY REFERENCES users(iduser) ON DELETE CASCADE,
    residence_city VARCHAR(50)
);

CREATE TABLE instructors (
    idinstructor INT PRIMARY KEY REFERENCES users(iduser) ON DELETE CASCADE
);

CREATE TABLE administrators (
    idadministrator INT PRIMARY KEY REFERENCES users(iduser) ON DELETE CASCADE
);

CREATE TABLE phone_numbers (
    idphonenumber INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(20) NOT NULL,
    idinstructor INT NOT NULL REFERENCES instructors(idinstructor) ON DELETE CASCADE
);

CREATE TABLE courses (
    idcourse INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    lesson_duration INT NOT NULL,
    idinstructor INT NOT NULL REFERENCES instructors(idinstructor),
    idroom INT NOT NULL REFERENCES rooms(idroom),
    idcoursetype INT NOT NULL REFERENCES course_types(idcoursetype)
);

CREATE TABLE lessons (
    idlesson INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    time TIME NOT NULL,
    idcourse INT NOT NULL REFERENCES courses(idcourse) ON DELETE CASCADE
);

CREATE TABLE memberships (
    idmembership INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE NOT NULL,
    idathlete INT NOT NULL REFERENCES athletes(idathlete),
    idmembershiptype INT NOT NULL REFERENCES membership_types(idmembershiptype),
    idadministrator INT NOT NULL REFERENCES administrators(idadministrator)
);

CREATE TABLE membership_courses (
    idmembership INT REFERENCES memberships(idmembership) ON DELETE CASCADE,
    idcourse INT REFERENCES courses(idcourse) ON DELETE CASCADE,
    PRIMARY KEY (idmembership, idcourse)
);

CREATE TABLE enrollments (
    idathlete INT REFERENCES athletes(idathlete) ON DELETE CASCADE,
    idcourse INT REFERENCES courses(idcourse) ON DELETE CASCADE,
    comment TEXT,
    PRIMARY KEY (idathlete, idcourse)
);

CREATE TABLE attendance (
    idathlete INT REFERENCES athletes(idathlete) ON DELETE CASCADE,
    idlesson INT REFERENCES lessons(idlesson) ON DELETE CASCADE,
    rating INT CHECK (rating BETWEEN 1 AND 5),
    PRIMARY KEY (idathlete, idlesson)
);

CREATE TABLE follows (
    idathlete INT REFERENCES athletes(idathlete) ON DELETE CASCADE,
    idathletefollowed INT REFERENCES athletes(idathlete) ON DELETE CASCADE,
    PRIMARY KEY (idathlete, idathletefollowed),
    CHECK (idathlete <> idathletefollowed)
);

CREATE TABLE monthly_awards (
    idaward INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month INT CHECK (month BETWEEN 1 AND 12),
    year INT,
    role VARCHAR(50),
    iduser INT NOT NULL REFERENCES users(iduser),
    UNIQUE (month, year, role)
);